"""Independent verification of the momentum cost-sensitivity check
(`research/checks/momentum_cost_sensitivity.py`).

This is a separate implementation path: it recomputes every segment's
walk-forward median and the universe-level results from a fresh
`walk_forward` implementation (not ``stress_segments``), then compares
against the artifact written by the check (`state/check_artifacts/
momentum_cost_sensitivity_results.json`). A mismatch would flag a defect
in the check.

Design of the independent path:
- Regime labels are reconstructed from ``closes`` using a re-implemented
  ``volatility_blocks`` (same algorithm as research.backtest, different code).
- Segments are reconstructed from labels using ``min_segment_bars``.
- Segment medians are computed via ``walk_forward`` directly on the segment
  slice -- no call to ``stress_segments`` or ``regime_stability.py``.
- The matched coin-flip null is re-generated by a re-implemented coin-flip
  signal generator (`random_signals`), seeded exactly as the framework does:
  seed = 42 + int(round(sum(params.values())) * 1000) for the single lookback
  param set.
- Gate 2 (daily-rebalance cost drag) is recomputed with a fully independent
  vectorized numpy implementation.
- All values are loaded from the check's artifact and compared.

This keeps the same inputs (dataset, seed, windows, segments, cost configs)
so a match confirms the check computed from those inputs; a mismatch would
flag an error in the check's pipeline.

Research / simulation only. No live trading or production execution.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
import research.backtest as bt
from research.data.preflight import load_manifest

DATASET_ID = "yf-ohlcv-universe-2009-to-2026-10-03"
SEED = 42
LOOKBACKS = (3, 5, 10)
TRAIN, TEST, WARM, OVERLAP = 252, 84, 60, 60
WINDOW = 60
N_BLOCKS = 4
MIN_SEGMENT_BARS = 400
INITIAL_CAPITAL = 1e6
OUTLIER_TOL = 0.05

ARTIFACT_PATH = Path.cwd() / "state" / "check_artifacts" / "momentum_cost_sensitivity_results.json"

# The same cost configs the check used, spelled out again.
ZERO_COST = bt.BacktestConfig()
REALISTIC_COST = bt.BacktestConfig(
    commission_per_trade=2.0,
    commission_per_share=0.003,
    slippage_cents=2.0,
    slippage_proportional=0.0005,
)
HEAVY_COST = bt.BacktestConfig(
    commission_per_trade=4.0,
    commission_per_share=0.006,
    slippage_cents=4.0,
    slippage_proportional=0.001,
)
COST_CONFIGS = [
    ("zero", ZERO_COST),
    ("realistic", REALISTIC_COST),
    ("heavy", HEAVY_COST),
]


def vol_blocks(closes, n_blocks, window):
    """Re-implementation of research.backtest.volatility_blocks."""
    n = len(closes)
    block_size = n // n_blocks
    bar_vols = []
    for i in range(n):
        if i < window:
            bar_vols.append(0.0)
        else:
            bar_vols.append(
                float(np.std(np.log(closes[i - window : i]), ddof=1)) * np.sqrt(252.0))
    active = [v for v in bar_vols if v > 0]
    series_med = float(np.median(active))
    labels = []
    for i in range(n):
        if i < window:
            labels.append("insufficient")
        else:
            b = i // block_size
            s, e = b * block_size, (b + 1) * block_size
            bmed = float(
                np.median([v for v in bar_vols[s:e] if v > 0])
                if e - s > window else 0.0)
            labels.append("turbulent" if bmed > series_med else "calm")
    return labels


def segments_from_labels(labels, min_segment_bars):
    runs = []
    cur = labels[0]
    run_start = 0
    for i in range(1, len(labels)):
        if labels[i] != cur:
            if i - run_start >= min_segment_bars:
                runs.append((cur, run_start, i))
            cur = labels[i]
            run_start = i
    if len(labels) - run_start >= min_segment_bars:
        runs.append((cur, run_start, len(labels)))
    return runs


def momentum_signals_independent(closes, lookback):
    """Fresh implementation of the momentum signal."""
    n = len(closes)
    out = [bt.Signal(date=i + 1, weight=0.0) for i in range(n)]
    lookback = int(lookback)
    for i in range(lookback, n):
        ret = float(np.mean(np.log(closes[i - lookback + 1 : i + 1])))
        out[i] = bt.Signal(date=i + 1, weight=1.0 if ret > 0 else -1.0)
    return out


def coin_flip_signals(n, seed):
    """Independent re-implementation of the coin-flip null signal."""
    rng = np.random.default_rng(seed)
    weights = rng.choice([-1.0, 0.0, 1.0], size=n, p=[1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0])
    return [bt.Signal(date=i + 1, weight=float(w)) for i, w in enumerate(weights)]


def param_seed_for_lookback(lookback, base_seed=42):
    """Same deterministic seed mapping the framework uses for the null."""
    return base_seed + int(round(float(lookback) * 1000))


def segment_medians(asset, runs, lookback, cfg):
    """Fresh walk-forward median per segment for one asset/lookback/config.

    Returns (rounded_medians, unrounded_medians, seg_folds); the framework
    computes candidate_dispersion from the unrounded medians and rounds only
    for reporting, so the dispersion must be recomputed from unrounded values.
    """
    bars, dates = bt.load_ticker(asset)
    closes = bars.closes_array()
    signals = momentum_signals_independent(closes, lookback)
    rounded = []
    unrounded = []
    seg_folds = []
    for lab, s, e in runs:
        seg_bars = list(bars)[s:e]
        seg_signals = signals[s:e]
        res = bt.walk_forward(
            seg_bars, seg_signals, train_window=TRAIN, test_window=TEST,
            warmup=WARM, overlap_window=OVERLAP, cfg=cfg)
        log = np.array([np.log1p(np.clip(f.metrics["total_return"], -1.0 + 1e-12, None))
                        for f in res.folds], dtype=np.float64)
        rounded.append(round(float(np.median(log)), 3))
        unrounded.append(float(np.median(log)))
        seg_folds.append(len(res.folds))
    return rounded, unrounded, seg_folds


def null_median_segment(seg_bars, seg_signals, train, test, warm, overlap, cfg,
                        lookback):
    """Fresh walk-forward median of the coin-flip null on one segment.

    Match the framework's ``stress_segments`` null path: ``noise_benchmark``
    is run with warmup=0 / overlap_window=0 (not the candidate's warmup=60 /
    overlap=60), so use those values here to reproduce the artifact.
    """
    n = len(seg_bars)
    pseed = param_seed_for_lookback(lookback)
    noise = coin_flip_signals(n, pseed)
    res = bt.walk_forward(
        seg_bars, noise, train_window=train, test_window=test,
        warmup=0, overlap_window=0, cfg=cfg)
    log = np.array([np.log1p(np.clip(f.metrics["total_return"], -1.0 + 1e-12, None))
                    for f in res.folds], dtype=np.float64)
    return round(float(np.median(log)), 3), float(np.median(log))


def verdict_from(medians_unrounded, cand_disp, null_disp):
    """Regenerate the regime-stability verdict from recomputed quantities.

    cand_disp / null_disp are the raw std of (unrounded) medians; the framework
    compares these raw dispersions against the 2x-null threshold (it rounds
    only for reporting), so compare on raw values.
    """
    if all(abs(m) <= OUTLIER_TOL for m in medians_unrounded):
        return "CONSISTENT_WITH_NOISE"
    if cand_disp > 2.0 * null_disp:
        return "REGIME_DEPENDENT"
    if all(m < 0 for m in medians_unrounded):
        return "REGIME_STABLE_LOSS"
    return "REGIME_STABLE"


def load_artifact():
    with open(ARTIFACT_PATH) as f:
        return json.load(f)


def main():
    np.random.seed(42)
    artifact = load_artifact()
    assert artifact["dataset_id"] == DATASET_ID, "manifest id mismatch"
    assert artifact["lookbacks"] == list(LOOKBACKS), "lookback set mismatch"

    print("=== 1. Per-asset Gate 1 recomputation (AMZN/JPM, walk_forward path) ===")
    all_ok = True

    for asset in ["AMZN", "JPM"]:
        bars, dates = bt.load_ticker(asset)
        closes = bars.closes_array()
        labels = vol_blocks(closes, N_BLOCKS, WINDOW)
        runs = segments_from_labels(labels, MIN_SEGMENT_BARS)
        lbls = [lab for lab, _, _ in runs]

        for lookback in LOOKBACKS:
            for label, cfg in COST_CONFIGS:
                pub = artifact["per_asset"][asset]["momentum"][str(lookback)][label]
                pub_lbls = pub["segments"]

                # Candidate recomputation via fresh walk-forward loop.
                cand_medians_r, cand_medians_u, cand_folds = segment_medians(
                    asset, runs, lookback, cfg)

                # Null recomputation via fresh coin-flip walk-forward loop.
                bars_list = list(bars)
                null_medians_r = []
                null_medians_u = []
                for lab, s, e in runs:
                    seg_bars = bars_list[s:e]
                    seg_signals = [bt.Signal(date=1, weight=0.0)] * len(seg_bars)
                    nm_r, nm_u = null_median_segment(
                        seg_bars, seg_signals, TRAIN, TEST, WARM, OVERLAP, cfg,
                        lookback)
                    null_medians_r.append(nm_r)
                    null_medians_u.append(nm_u)

                # The framework computes dispersions from the UNROUNDED medians
                # and rounds only for reporting, then compares cand_disp > 2x
                # null_disp on raw values; match that exactly.
                cand_disp = float(np.std(np.array(cand_medians_u, dtype=np.float64)))
                null_disp = float(np.std(np.array(null_medians_u, dtype=np.float64)))
                regen_verdict = verdict_from(cand_medians_u, cand_disp, null_disp)

                cand_status = "MATCH" if cand_medians_r == pub["medians"] else "MISMATCH"
                null_status = "MATCH" if null_medians_r == pub["null_medians"] else "MISMATCH"
                lbl_status = "MATCH" if lbls == pub_lbls else "MISMATCH"
                v_status = "MATCH" if regen_verdict == pub["verdict"] else "MISMATCH"

                if not (cand_status == "MATCH" and null_status == "MATCH"
                        and lbl_status == "MATCH" and v_status == "MATCH"):
                    all_ok = False
                    print("  [DEBUG] {} lb={} cfg={}: runs={} lbls={}".format(
                        asset, lookback, label, len(runs), lbls))
                    print("  [DEBUG] {} lb={} cfg={}: pub medians={} re={} cand {}".format(
                        asset, lookback, label, pub["medians"], cand_medians_r, cand_status))
                    print("  [DEBUG] {} lb={} cfg={}: pub nulls={} re={} null {}".format(
                        asset, lookback, label, pub["null_medians"], null_medians_r, null_status))
                    print("  [DEBUG] {} lb={} cfg={}: pub verdict={} re={} verdict {}".format(
                        asset, lookback, label, pub["verdict"], regen_verdict, v_status))

                print("  {} lookback={} {} medians {} -> {} | null {} -> {} | "
                      "verdict {} (pub {}) [{} {} {} {}]"
                      .format(asset, lookback, label, cand_medians_r, cand_status,
                              null_medians_r, null_status, regen_verdict, pub["verdict"],
                              cand_status, null_status, lbl_status, v_status))

    # Universe Gate 1: recompute lookback-5 realistic cells for all 10 assets
    # and regenerate verdicts from the artifact's recomputed medians/nulls.
    print("\n=== 2. Universe Gate 1 recomputation (lookback=5, realistic) ===")
    tickers = {}
    m = load_manifest()
    for entry in m["entries"]:
        tickers[entry["ticker"]] = bt.load_ticker(entry["ticker"])[0]

    cfg = REALISTIC_COST
    for lookback, lb_cells in artifact["universe"].items():
        for label, cell in lb_cells.items():
            if lookback != "5" or label != "realistic":
                continue
            for ticker in cell["per_asset"]:
                bars, dates = bt.load_ticker(ticker)
                closes = bars.closes_array()
                labels = vol_blocks(closes, N_BLOCKS, WINDOW)
                runs = segments_from_labels(labels, MIN_SEGMENT_BARS)
                lbls = [lab for lab, _, _ in runs]
                pub = cell["per_asset"][ticker]

                cand_medians_r, cand_medians_u, _ = segment_medians(
                    ticker, runs, int(lookback), cfg)
                bars_list = list(bars)
                null_medians_r = []
                null_medians_u = []
                for lab, s, e in runs:
                    seg_bars = bars_list[s:e]
                    seg_signals = [bt.Signal(date=1, weight=0.0)] * len(seg_bars)
                    nm_r, nm_u = null_median_segment(
                        seg_bars, seg_signals, TRAIN, TEST, WARM, OVERLAP, cfg,
                        int(lookback))
                    null_medians_r.append(nm_r)
                    null_medians_u.append(nm_u)

                cand_disp = float(np.std(np.array(cand_medians_u, dtype=np.float64)))
                null_disp = float(np.std(np.array(null_medians_u, dtype=np.float64)))
                regen_verdict = verdict_from(cand_medians_u, cand_disp, null_disp)

                status = "MATCH" if cand_medians_r == pub["medians"] else "MISMATCH"
                null_status = "MATCH" if null_medians_r == pub["null_medians"] else "MISMATCH"
                verdict_status = "MATCH" if regen_verdict == pub["verdict"] else "MISMATCH"
                if status != "MATCH" or null_status != "MATCH" or verdict_status != "MATCH":
                    all_ok = False
                    print("  [DEBUG] {} medians {} re {} cand {}".format(
                        ticker, pub["medians"], cand_medians_r, status))
                print("  {}: medians {} -> {} | null {} -> {} | verdict {} (pub {}) [{} {} {}]"
                      .format(ticker, cand_medians_r, status, null_medians_r, null_status,
                              regen_verdict, pub["verdict"], status, null_status, verdict_status))

    # Gate 2: independent vectorized recomputation of the daily-rebalance cost drag.
    print("\n=== 3. Gate 2 independent recomputation (daily-rebalance cost drag) ===")
    bars, dates = bt.load_ticker("AAPL")
    closes = bars.closes_array()
    n = len(closes)

    for lookback in LOOKBACKS:
        sigs = momentum_signals_independent(closes, lookback)
        for label, cfg in COST_CONFIGS:
            pub = artifact["daily_rebalance"][str(lookback)][label]

            # Independent vectorized implementation.
            weight = np.array([s.weight for s in sigs])
            mask = np.abs(weight) > 1e-12
            i = np.nonzero(mask[:-1])[0]
            entry = closes[i] + cfg.slippage_cents / 100.0 + closes[i] * cfg.slippage_proportional
            exit_ = closes[i + 1] + cfg.slippage_cents / 100.0 + closes[i + 1] * cfg.slippage_proportional
            shares = INITIAL_CAPITAL / entry
            gross_pnl = weight[i] * shares * (exit_ - entry)
            cost = (2.0 * (cfg.commission_per_trade + np.abs(weight[i]) * shares
                           * cfg.commission_per_share)
                    + np.abs(weight[i]) * shares * (entry - closes[i])
                    + np.abs(weight[i]) * shares * (exit_ - closes[i + 1]))
            net_pnl = gross_pnl - cost
            net_rets = np.log1p(net_pnl / INITIAL_CAPITAL)
            gross_rets = np.log1p(gross_pnl / INITIAL_CAPITAL)

            # Delta is the check's own (unrounded-medians) net minus gross,
            # rounded once: match that rounding exactly.
            med = round(float(np.median(net_rets)), 6)
            med_gross = round(float(np.median(gross_rets)), 6)
            mean_cost = round(float(np.mean(cost)), 2)
            mean_cost_pct = round(float(np.mean(cost) / INITIAL_CAPITAL), 6)
            delta = round(float(np.median(net_rets)) - float(np.median(gross_rets)), 6)

            med_status = "MATCH" if med == pub["median_daily_net_log_return"] else "MISMATCH"
            gross_status = "MATCH" if med_gross == pub["median_daily_gross_log_return"] else "MISMATCH"
            cost_status = "MATCH" if mean_cost == pub["mean_round_trip_cost_dollars"] else "MISMATCH"
            pct_status = "MATCH" if mean_cost_pct == pub["mean_round_trip_cost_pct_of_capital"] else "MISMATCH"
            delta_status = "MATCH" if delta == pub["net_vs_gross_delta"] else "MISMATCH"

            if not all(s == "MATCH" for s in
                       (med_status, gross_status, cost_status, pct_status, delta_status)):
                all_ok = False
                print("  [DEBUG] lookback={} {} net {} pub {} -> {}".format(
                    lookback, label, med, pub["median_daily_net_log_return"], med_status))

            print("  lookback={} {} med_net={:+.6f} (pub {:+.6f}) [{}] "
                  "mean_cost=${:,.0f}/day (pub ${:,.0f}) [{}] delta={:+.6f} (pub {:+.6f}) [{}]"
                  .format(lookback, label, med, pub["median_daily_net_log_return"], med_status,
                          mean_cost, pub["mean_round_trip_cost_dollars"], cost_status,
                          delta, pub["net_vs_gross_delta"], delta_status))

    # Determinism: rerun the full verifier path for AMZN/JPM lookback 5 realistic.
    print("\n=== 4. Determinism (rerun verifier path, compare) ===")
    bars, dates = bt.load_ticker("AMZN")
    closes = bars.closes_array()
    labels = vol_blocks(closes, N_BLOCKS, WINDOW)
    runs = segments_from_labels(labels, MIN_SEGMENT_BARS)
    m1_r, m1_u, f1 = segment_medians("AMZN", runs, 5, REALISTIC_COST)
    m2_r, m2_u, f2 = segment_medians("AMZN", runs, 5, REALISTIC_COST)
    print("  AMZN lookback=5 realistic medians r1: {}; r2: {} -> {}".format(
        m1_r, m2_r, "identical" if m1_r == m2_r else "DIFFERENT"))
    if m1_r != m2_r:
        all_ok = False
    assert m1_r == m2_r, "verification path not deterministic"

    print()
    if all_ok:
        print("All independent recomputations MATCH the check artifact.")
    else:
        print("MISMATCH FOUND: the check artifact does not reproduce via the "
              "independent path. Investigate before admitting the results.")
        sys.exit(1)
    print("NOTE: research/simulation only. No live trading or production "
          "execution. Momentum cost-sensitivity independent verification: "
          "exploratory simulation.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
