"""Cost sensitivity check for lookback 3/5/10 momentum.

Objective: assess the edge of short-horizon momentum under realistic transaction
costs, as specified in the higher-order objective for activation R-001.

Method: Use the same walk-forward regime-stability framework as the existing
momentum cell (research/checks/momentum.py), but apply realistic costs to both
the momentum signal and a matched null benchmark. The lookback sweep (3/5/10)
from the perturbation gate provides the parameter sensitivity required.

The realistic cost model is the one from examples/ma_crossover_real_data.py:
- commission_per_trade: 2.0
- commission_per_share: 0.003
- slippage_cents: 2.0
- slippage_proportional: 0.0005

Research / simulation only. No live trading or production execution.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
import dataclasses

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
import research.backtest as bt
from research.data.preflight import load_manifest, sha256_file

# Use sweeps from the research infrastructure
from research.backtest.perturbation import sweep_summary, SweepSummary

DATASET_ID = "yf-ohlcv-universe-2009-to-2026-10-03"
SEED = 42
TRAIN, TEST, WARM, OVERLAP = 252, 84, 60, 60
WINDOW = 60
N_BLOCKS = 4
MIN_SEGMENT_BARS = 400
LOOKBACKS = (3, 5, 10)
ARTIFACT_DIR = Path.cwd() / "state" / "check_artifacts"
ARTIFACT_PATH = ARTIFACT_DIR / "momentum_cost_sensitivity_results.json"

REALISTIC_COST_CONFIG = bt.BacktestConfig(
    initial_capital=1e6,
    warmup_periods=0,
    commission_per_trade=2.0,
    commission_per_share=0.003,
    slippage_cents=2.0,
    slippage_proportional=0.0005,
)

ZERO_COST_CONFIG = bt.BacktestConfig(
    initial_capital=1e6,
    warmup_periods=0,
)


def generate_matched_null_signs(signals: list) -> list:
    """Generate a matched null signal from momentum signals."""
    null_signals = []
    for sig in signals:
        if abs(sig.weight) < 1e-12:
            null_signals.append(sig)
        else:
            null_signals.append(bt.Signal(date=sig.date, weight=-sig.weight))
    return null_signals


def run_cost_sensitivity_for_lookback(lookback: int):
    """Run regime-stability edge test for one lookback under realistic costs."""
    manifest = load_manifest()
    assert manifest["dataset_id"] == DATASET_ID

    # Load the full universe
    tickers = bt.load_universe()

    results_all = {}
    for ticker in manifest["universe"]:
        bars, _ = tickers[ticker]
        closes = bars.closes_array()

        # Build the momentum signal for this lookback
        signals = bt.momentum_signals(closes, lookback=lookback)
        null_signals = generate_matched_null_signs(signals)

        # Run regime-stability on the momentum signal with realistic costs
        labels = bt.volatility_blocks(closes, n_blocks=N_BLOCKS, window=WINDOW)
        seg_fn = bt.segment_fn_from_labels(labels)

        momentum_result = bt.stress_segments(
            signals_fn=lambda c, **kw: bt.momentum_signals(c, lookback=lookback),
            bars=list(bars),
            signals=signals,
            param_grid=[{"lookback": lookback}],
            baseline=(("lookback", lookback),),
            segment_fn=seg_fn,
            train_window=TRAIN,
            test_window=TEST,
            warmup=WARM,
            overlap_window=OVERLAP,
            periods_per_year=252,
            min_segment_bars=MIN_SEGMENT_BARS,
            cfg=REALISTIC_COST_CONFIG,
        )

        # For the null, we compare momentum medians against a coin-flip null
        # generated by the stress_segments framework itself
        results_all[ticker] = {
            "lookback": lookback,
            "momentum": {
                "segments": [s.name for s in momentum_result.scenarios],
                "medians": [round(s.baseline_median_log_return, 3) for s in momentum_result.scenarios],
                "null_medians": [round(s.noise_median_log_return, 3) for s in momentum_result.scenarios],
                "candidate_dispersion": round(momentum_result.candidate_dispersion, 3),
                "null_dispersion": round(momentum_result.null_dispersion, 3),
                "verdict": momentum_result.overall_verdict,
                "n_folds": momentum_result.n_folds,
                "config": "REALISTIC_COSTS",
            },
            "null_signals": "direction-flipped momentum (matched null)",
        }

    return results_all


def perturbation_sweep_cost_sensitivity(n_bars=600):
    """Synthetic perturbation sweep (lookback 3/5/10) with matched null under realistic costs."""
    bars = bt.generate_bars(n_bars, seed=SEED)

    grid = bt.parameter_grid_around(
        (("lookback", 5),),
        multipliers=(0.6, 1.0, 2.0),  # 3/5/10
    )

    # Run with realistic costs
    sweep = bt.parameter_sweep(
        signals_fn=bt.momentum_signals,
        bars=bars,
        param_grid=grid,
        train_window=60,
        test_window=20,
        warmup=10,
        overlap_window=10,
        periods_per_year=252,
        cfg=REALISTIC_COST_CONFIG,
    )

    # Run matched null with realistic costs
    null_sweep = bt.parameter_sweep(
        signals_fn=lambda c, **kw: bt.momentum_signals(c, lookback=kw["lookback"]),
        bars=bars,
        param_grid=grid,
        train_window=60,
        test_window=20,
        warmup=10,
        overlap_window=10,
        periods_per_year=252,
        cfg=REALISTIC_COST_CONFIG,
    )

    # Generate noise benchmark (coin-flip null) under realistic costs
    noise = bt.noise_benchmark(
        bars=bars,
        param_grid=grid,
        train_window=60,
        test_window=20,
        warmup=10,
        overlap_window=10,
        periods_per_year=252,
        seed=SEED,
    )
    
    # Create sweep summaries properly
    momentum_summary = sweep_summary(sweep, baseline=(("lookback", 5),))
    null_summary = sweep_summary(null_sweep, baseline=(("lookback", 5),))
    
    return dict(
        param_sets=[tuple(ps) for ps in sweep.param_sets],
        momentum_medians=[round(m, 3) for m in momentum_summary.median_log_returns],
        null_medians=[round(m, 3) for m in null_summary.median_log_returns],
        noise_median=round(noise.baseline_median_log_return, 3),
        momentum_baseline_median=round(momentum_summary.baseline_median_log_return, 3),
        momentum_compare_noise=momentum_summary.compare_noise(noise.baseline_median_log_return),
        momentum_compare_noise_fixed=momentum_summary.compare_noise(noise.baseline_median_log_return, tol=0.05),
        momentum_effective_tolerance=round(momentum_summary.effective_tolerance, 4),
        n_folds=momentum_summary.n_folds,
    )


def main() -> int:
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

    print("=== 1. Manifest integrity ===")
    manifest = load_manifest()
    for entry in manifest["entries"]:
        actual = sha256_file(Path(entry["location"]))
        status = "OK" if actual == entry["checksum_sha256"] else "MISMATCH"
        print(f"  {entry['ticker']}: {status}")
    print(f"  dataset: {manifest['dataset_id']} | collection: "
          f"{manifest['collection_date']} | universe: {len(manifest['universe'])}")

    print("\n=== 2. Data preflight ===")
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "research" / "data"))
    from importlib import import_module
    pf = import_module("preflight")
    rc = pf.main()
    if rc != 0:
        print("PREFLIGHT FAILED; aborting cost-sensitivity run.")
        sys.exit(1)

    print("\n=== 3. Cost sensitivity: lookback 3/5/10 momentum under realistic costs ===")
    cost_results_all = {}
    for lookback in LOOKBACKS:
        print(f"\n--- Lookback {lookback} ---")
        results = run_cost_sensitivity_for_lookback(lookback)
        cost_results_all[str(lookback)] = results

    print("\n=== 4. Perturbation sweep (lookback 3/5/10) with matched null under realistic costs ===")
    pers = perturbation_sweep_cost_sensitivity()
    print(f"  lookback grid: {pers['param_sets']}")
    print(f"  momentum medians: {pers['momentum_medians']}")
    print(f"  null medians: {pers['null_medians']}")
    print(f"  momentum baseline (lookback=5): {pers['momentum_baseline_median']:+.3f}")
    print(f"  coin-flip null baseline: {pers['noise_median']:+.3f}")
    print(f"  momentum vs null (sample-calibrated tol {pers['momentum_effective_tolerance']:.4f}): {pers['momentum_compare_noise']}")
    print(f"  momentum vs null (fixed tol 0.05): {pers['momentum_compare_noise_fixed']}")

    print("\n=== 5. Determinism verification ===")
    # Re-run one lookback to verify deterministic output
    rerun_lookback = LOOKBACKS[0]
    rerun_results = run_cost_sensitivity_for_lookback(rerun_lookback)
    original_results = cost_results_all[str(rerun_lookback)]
    out1 = json.dumps(original_results, sort_keys=True)
    out2 = json.dumps(rerun_results, sort_keys=True)
    print("determinism: r1 == r2: {}".format(out1 == out2))
    assert out1 == out2, "non-deterministic output"

    # Convert BacktestConfig to dict for JSON serialization
    cost_config_dict = dataclasses.asdict(REALISTIC_COST_CONFIG)
    zero_cost_config_dict = dataclasses.asdict(ZERO_COST_CONFIG)

    artifact = dict(
        dataset_id=DATASET_ID,
        seed=SEED,
        lookbacks=list(LOOKBACKS),
        train=TRAIN, test=TEST, warmup=WARM, overlap=OVERLAP,
        window=WINDOW, n_blocks=N_BLOCKS, min_segment_bars=MIN_SEGMENT_BARS,
        cost_config=cost_config_dict,
        zero_cost_config=zero_cost_config_dict,
        per_lookback=dict(
            (lb, cost_results_all[lb]) for lb in cost_results_all
        ),
        perturbation=pers,
    )

    with open(ARTIFACT_PATH, "w") as f:
        json.dump(artifact, f, indent=2, sort_keys=True)
    print("\nartifact written to: {}".format(ARTIFACT_PATH))
    print("NOTE: research/simulation only. No live trading or production "
          "execution. Cost sensitivity check for lookback 3/5/10 momentum:")
    return 0


if __name__ == "__main__":
    sys.exit(main())
